[Service]
Environment=X402_MODE=live
Environment=X402_EVM_NETWORKS=
Environment=X402_SVM_NETWORK=solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1
Environment=X402_SVM_PAY_TO=39ayJ2S5h6VpzxWtAGkKFHTSiHMYt73oJNvpAkTp8Qc8
Environment=X402_FACILITATOR_URL=https://x402.org/facilitator
